version: 2
jobs:
  build:
    working_directory: ~/subhub
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build App
          command: yarn run build
